// Perform a suicide burn such that you stop thrusting as soon as you reach the ground.
// todo do the math
LOCK THROTTLE TO 0.0.
LOCK STEERING TO SHIP:SRFRETROGRADE.
WAIT UNTIL VANG(SHIP:SRFRETROGRADE, SHIP:FACING:VECTOR) < 0.25.
LOCK THROTTLE TO 1.0.

WAIT UNTIL SHIP:ALTITUDE < 100 OR SHIP:GROUNDSPEED < 10

LOCK THROTTLE TO 0.0.
SET SHIP:CONTROL:PILOTMAINTHROTTLE TO 0.
